### ISSUE TITLE
[FEATURE]Documentation: how to delete everything if things goes really wrong

### ISSUE THREAD

**Issue by haavardeide** [oslokommune/okctl#172]
**Is your feature request related to a problem? Please describe.**
If `okctl delete cluster dev` fails there are no guidelines on how to get unstuck from various cloudformation states

**Describe the solution you'd like**
Documentation on what to delete manually, in which order, and how to get unstuck from possible problems that might arise when using okctl when setting up a cluster or a application. I got a recipe on slack from Julius, but this should be readily available for everyone

**Comment by paulbes** [comment]
Also tracked via: https://trello.com/c/0O9tsMfi/156-improve-user-documentation

**Comment by paulbes** [comment]
**NB:** The following text will be moving into `userdocs` once we have accepted that it provides sufficient value.

# Deleting a cluster with `okctl` has failed

The delete operation may have failed for several different reasons. In the following sections, we list some of the common causes of problems and possible remedies.

## Delete all Kubernetes resources

Delete everything in all namespaces except `kube-system`. In `kube-system`, some of the core components, such as `AWS load balancer controller` are running. These controllers create AWS resources on your behalf. By removing all resources from all namespaces, we allow these services to clean up themselves.

```bash
for each in $(kubectl get ns -o jsonpath="{.items[*].metadata.name}" | grep -v kube-system);
do
  kubectl delete ns $each
done
```

## Delete the cloud formation stacks in reverse order

Log in to the AWS console for your account, then go to `Cloud Formation > Stacks`. If your AWS account contains many stacks, filter the list by `okctl` and the cluster name and environment.

Start deleting the stacks in order from _newest_ to _oldest_, if a stack ends up in a state where the delete operation fails. Take a closer look at the events generated by the delete operation on the stack. Frequently you will find a resource that has failed to delete for some reason. Follow this resource to its corresponding page. Maybe a subnet has failed to delete because there are active network interfaces on it. By following the resource and trying to delete it manually, you will be given additional information. Perhaps you need to disconnect the interfaces from an EC2 machine first, etc. Once you have resolved the problem, go back and try to delete the cloud formation stack again.

## List all AWS resources created by `okctl`

It is possible to list all AWS resources created by `okctl` by running the command below. This can be a useful command to run to find any missing resources.

```bash
aws resourcegroupstaggingapi get-resources \
> --tag-filters Key=alpha.okctl.io/okctl-version,Values=dev \
> --tags-per-page 100
```

**Comment by paulbes** [comment]
@deifyed could you please add any additional details you might have?

**Comment by deifyed** [comment]
Missing information about the Fargate Profile

**Comment by deifyed** [comment]
Also, it might be worth knowing that some SSM parameters and some ACM certificates might linger
